name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        env:
          MY_SECRET: ${{ secrets.hello-world }}
        run: |
          echo "Hello World!"
          echo "The secret value is $MY_SECRET"
